New/home
CodersCamp2021/team-lp-project-4 pull request #6
Opened 2022-04-10 19:58 UTC by macjank

2022-04-10 23:39 UTC, kubaczerwinski77 commented on src/components/Home/HomeGame.tsx
> +  return (
I would suggest that styling
```
<Box
      component={Link}
      to={`/games/${id}`}
      sx={{
        backgroundColor: '#1F1F1FBB',
        borderRadius: '5px',
      }}
    >
      <Image radius={3} p={5} src={src} alt={title} />
    </Box>
```

2022-04-10 23:51 UTC, kubaczerwinski77 requested changes
Just two small style-like changes, the rest - great 💯

2022-04-10 23:51 UTC, kubaczerwinski77 commented on src/components/Home/Home.tsx
> +        <Text className={classes.subtitle} color="#cccccc">
Changed subtitle to look more like in the Figma project
```
<Text
          className={classes.subtitle}
          color="#cccccc"
          transform="uppercase"
          sx={{ fontWeight: 'bold', letterSpacing: '6px' }}
        >
          Discover, review,
          <br /> enjoy yourself
</Text>
```

2022-04-12 17:59 UTC, pastepi requested changes

2022-04-12 17:59 UTC, pastepi commented on src/App.tsx
Font is still default, we decided to use Poppins, you can check how I managed to implement it [here](https://github.com/CodersCamp2021/team-lp-project-4/blob/new/games-view/src/App.tsx) (don't forget to install the font from [fontsource](https://fontsource.org/)).

2022-04-12 19:07 UTC, pastepi approved these changes

2022-04-12 19:39 UTC, merged